name: Release

on:
  push:
    branches:
      - release  # Triggers only when code is pushed to `release` branch

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Publish to NPM & GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Package
        run: bun run build

      - name: Ensure `dist/` Exists
        run: ls -la dist

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get Version from package.json
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "### Changes in v${{ env.VERSION }}\n\n- See commit history for details."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
